### ISSUE TITLE
Handle Songbooks

### ISSUE THREAD

**Issue by gorgobacka** [PatWie/digitalmusicstand#2]
This is an really cool project. It's simple and very lightweight. I'm plan to use it on a RPi together with my piano.

However, most of my scanned sheet music is arranged in complete songbooks. And I don't want to cut them.

Do you have some ideas how to deal with those?

One idea that came to my mind is to provide a small text file with the same filename as the pdf that includes the annotations (one song per line). Something like:

```
Line 1: artist<tab>title<tab>start_page<tab>end_page
Line 2: ...
```

And then only convert those pages on the fly.

But I don't know if this is possible.

**Comment by PatWie** [comment]
That's how I use it with Pianoteq on a RPi and a Monitor above my piano :-)

This sounds like a good idea to me! I also have some trouble with repeating bars when I need to skip from page 5 back to page 2. Ideally, I would skip automatically to the correct page `1 -> 2 -> 3 -> 4 -> 5 -> 2 -> 3 -> 4 ->  ...`

What about adding a yaml file to each pdf like
```yaml
# content of filename.yml
- artist: example artist 1
  title: example title 1
  pages: [1,2,3,4,3,4,5] 
- artist: example artist 2
  title: example title 2
  pages: [6,7] 
- artist: example artist 3
  title: example title 3
  pages: [8,9,10,11,9,12] 
```

When reading in the files like `filename.pdf` it is possible to also read these additional metadata in `filename.yml`. But the even more elegant solution is to provide a function that uses the metadata from `filename.yml` and creates pdfs from them only once in a background-job. I want to avoid heavy processing when loading a sheet.

Would it be ok to let the digital music stand automatically cut the songbook into pieces without touching the original file?
